// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:11:28 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_N_Mux_32_2_0_4( in2, ctrl1, out1 );

    input [31:0] in2;
    input ctrl1;
    output [31:0] out1;
    reg [31:0] out1;

    
    always @(ctrl1 or in2)
      begin : dummy_N_Mux_32_2_0_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = 32'd0000000512;
            end
          default: 
            begin
              out1 = in2;
            end
        endcase
      end

endmodule



