// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:11:28 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_Add_3U_8_4( in1, out1 );

    input [2:0] in1;
    output [2:0] out1;

    
    // instance: drive_out1
    assign out1 = in1 + 3'd1;

endmodule

