// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:09:44 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_Not_1U_1U_4( in1, out1 );

    input in1;
    output out1;

    
    // instance: drive_out1
    assign out1 = !in1;

endmodule

