// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:12:12 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_Add_9Ux3U_9U_4( in2, in1, out1 );

    input [8:0] in2;
    input [2:0] in1;
    output [8:0] out1;

    
    // instance: drive_out1
    assign out1 = in2 + {6'b000000, in1};

endmodule


