// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:12:13 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_Add_2U_7_4( in1, out1 );

    input [1:0] in1;
    output [1:0] out1;

    
    // instance: drive_out1
    assign out1 = in1 + 2'd1;

endmodule

