// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:12:12 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_N_Muxb_1_2_3_4( in3, in2, ctrl1, out1 );

    input in3;
    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    always @(ctrl1 or in2 or in3)
      begin : dummy_N_Muxb_1_2_3_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule



