// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:10:39 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_GreaterThan_32Sx11S_1U_4( in2, in1, out1 );

    input [31:0] in2;
    input [10:0] in1;
    output out1;

    
    // instance: drive_out1
    assign out1 = (in2 > {{ 21 {in1[10]}}, in1} ^ (in1[10] ^ in2[31]));

endmodule



