// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:10:29 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_Add_16Ux2U_16U_4( in2, in1, out1 );

    input [15:0] in2;
    input [1:0] in1;
    output [15:0] out1;

    
    // instance: drive_out1
    assign out1 = in2 + {14'b00000000000000, in1};

endmodule

