// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:09:27 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_N_Mux_1_2_2_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    always @(ctrl1 or in2)
      begin : dummy_N_Mux_1_2_2_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 1'b1;
            end
        endcase
      end

endmodule


