// Generated by stratus_hls 24.02-s004  (104273.080414)
// Mon Dec  1 16:11:17 2025
// from ../src/dummy.cpp

`timescale 1ps / 1ps


module dummy_Add_32Sx1U_32S_4( in2, in1, out1 );

    input [31:0] in2;
    input in1;
    output [31:0] out1;

    
    // instance: drive_out1
    assign out1 = in2 + {31'b0000000000000000000000000000000, in1};

endmodule

